/**
 * data.js
 * Base de dados do catálogo pessoal de filmes.
 * Cada item representa um filme já assistido ou na lista de "quero assistir".
 * As sinopses foram escritas de forma resumida e autoral para fins deste projeto.
 */

const CATALOGO_FILMES = [
  {
    id: 1,
    titulo: "Blade Runner 2049",
    ano: 2017,
    diretor: "Denis Villeneuve",
    generos: ["ficcao", "drama"],
    duracao: 164,
    nota: 5,
    status: "assistido",
    sinopse: "Um replicante da nova geração descobre um segredo capaz de mergulhar a sociedade em caos e parte à procura de um antigo agente aposentado.",
    corTema: "#3c6e91"
  },
  {
    id: 2,
    titulo: "Parasita",
    ano: 2019,
    diretor: "Bong Joon-ho",
    generos: ["drama", "suspense"],
    duracao: 132,
    nota: 5,
    status: "assistido",
    sinopse: "Uma família de baixa renda se infiltra, aos poucos, na rotina de uma família rica, até que um evento inesperado muda tudo.",
    corTema: "#4a5d3a"
  },
  {
    id: 3,
    titulo: "Interestelar",
    ano: 2014,
    diretor: "Christopher Nolan",
    generos: ["ficcao", "aventura"],
    duracao: 169,
    nota: 5,
    status: "assistido",
    sinopse: "Um grupo de exploradores usa uma passagem recém-descoberta no espaço-tempo para tentar garantir a sobrevivência da humanidade.",
    corTema: "#1f2d4d"
  },
  {
    id: 4,
    titulo: "A Forma da Água",
    ano: 2017,
    diretor: "Guillermo del Toro",
    generos: ["romance", "fantasia"],
    duracao: 123,
    nota: 4,
    status: "assistido",
    sinopse: "Uma faxineira muda desenvolve uma conexão afetiva incomum com uma criatura anfíbia mantida em um laboratório secreto.",
    corTema: "#255c5c"
  },
  {
    id: 5,
    titulo: "Whiplash: Em Busca da Perfeição",
    ano: 2014,
    diretor: "Damien Chazelle",
    generos: ["drama", "musical"],
    duracao: 107,
    nota: 5,
    status: "assistido",
    sinopse: "Um jovem baterista de jazz é empurrado ao limite por um professor extremamente exigente em busca da excelência.",
    corTema: "#7a2020"
  },
  {
    id: 6,
    titulo: "Duna",
    ano: 2021,
    diretor: "Denis Villeneuve",
    generos: ["ficcao", "aventura"],
    duracao: 155,
    nota: 4,
    status: "assistido",
    sinopse: "O herdeiro de uma casa nobre precisa proteger o recurso mais valioso da galáxia em um planeta desértico hostil.",
    corTema: "#8a6a3a"
  },
  {
    id: 7,
    titulo: "Oppenheimer",
    ano: 2023,
    diretor: "Christopher Nolan",
    generos: ["drama", "historia"],
    duracao: 180,
    nota: 0,
    status: "quero-assistir",
    sinopse: "A trajetória do físico J. Robert Oppenheimer e seu papel central no desenvolvimento da bomba atômica.",
    corTema: "#3a3a3a"
  },
  {
    id: 8,
    titulo: "Handred: Vidas Passadas",
    ano: 2023,
    diretor: "Celine Song",
    generos: ["romance", "drama"],
    duracao: 106,
    nota: 0,
    status: "quero-assistir",
    sinopse: "Duas pessoas que se conheceram na infância se reencontram décadas depois e reavaliam os caminhos que suas vidas tomaram.",
    corTema: "#5c3a5c"
  },
  {
    id: 9,
    titulo: "O Andarilho",
    ano: 2015,
    diretor: "Alejandro G. Iñárritu",
    generos: ["drama", "aventura"],
    duracao: 156,
    nota: 4,
    status: "assistido",
    sinopse: "Um caçador ferido e abandonado pela própria expedição luta para sobreviver e retornar à civilização.",
    corTema: "#4a4030"
  },
  {
    id: 10,
    titulo: "Coringa",
    ano: 2019,
    diretor: "Todd Phillips",
    generos: ["drama", "suspense"],
    duracao: 122,
    nota: 5,
    status: "assistido",
    sinopse: "Um comediante fracassado de Gotham City é empurrado, aos poucos, para uma espiral de isolamento e violência.",
    corTema: "#5c1f3a"
  },
  {
    id: 11,
    titulo: "Divertida Mente 2",
    ano: 2024,
    diretor: "Kelsey Mann",
    generos: ["animacao", "aventura"],
    duracao: 96,
    nota: 4,
    status: "assistido",
    sinopse: "As emoções de Riley precisam lidar com a chegada de novos sentimentos durante a fase da adolescência.",
    corTema: "#3a6e6e"
  },
  {
    id: 12,
    titulo: "Clube da Luta",
    ano: 1999,
    diretor: "David Fincher",
    generos: ["drama", "suspense"],
    duracao: 139,
    nota: 5,
    status: "assistido",
    sinopse: "Um homem insone e insatisfeito com a vida forma, ao lado de um vendedor de sabonetes, um clube clandestino de lutas.",
    corTema: "#2a2a2a"
  },
  {
    id: 13,
    titulo: "Divertida Mente",
    ano: 2015,
    diretor: "Pete Docter",
    generos: ["animacao", "aventura"],
    duracao: 95,
    nota: 4,
    status: "assistido",
    sinopse: "As emoções dentro da mente de uma garota de onze anos tentam guiá-la durante uma difícil mudança de cidade.",
    corTema: "#3a5c8a"
  },
  {
    id: 14,
    titulo: "Cidade de Deus",
    ano: 2002,
    diretor: "Fernando Meirelles",
    generos: ["drama", "historia"],
    duracao: 130,
    nota: 5,
    status: "assistido",
    sinopse: "A trajetória de moradores de uma favela carioca é acompanhada ao longo de duas décadas marcadas pela violência.",
    corTema: "#8a5c2a"
  },
  {
    id: 15,
    titulo: "Poor Things",
    ano: 2023,
    diretor: "Yorgos Lanthimos",
    generos: ["fantasia", "comedia"],
    duracao: 141,
    nota: 0,
    status: "quero-assistir",
    sinopse: "Uma jovem mulher trazida de volta à vida por um cientista excêntrico embarca em uma jornada de autodescoberta.",
    corTema: "#5c5c1f"
  },
  {
    id: 16,
    titulo: "Green Book",
    ano: 2018,
    diretor: "Peter Farrelly",
    generos: ["drama", "comedia"],
    duracao: 130,
    nota: 4,
    status: "assistido",
    sinopse: "Um motorista ítalo-americano é contratado para conduzir um pianista negro em turnê pelo sul dos EUA nos anos 1960.",
    corTema: "#1f5c3a"
  },

  // ---- Universo Marvel (MCU) ----
  { id: 100, titulo: "Homem de Ferro", ano: 2008, diretor: "Jon Favreau", generos: ["acao", "ficcao"], duracao: 126, nota: 5, status: "assistido", sinopse: "Um industrial bilionário constrói uma armadura tecnológica após ser capturado durante um conflito armado.", corTema: "#7a2020" },
  { id: 101, titulo: "O Incrível Hulk", ano: 2008, diretor: "Louis Leterrier", generos: ["acao", "ficcao"], duracao: 112, nota: 4, status: "assistido", sinopse: "Um cientista foge do exército americano enquanto tenta controlar a fera em que se transforma sob estresse.", corTema: "#7a2020" },
  { id: 102, titulo: "Homem de Ferro 2", ano: 2010, diretor: "Jon Favreau", generos: ["acao", "ficcao"], duracao: 124, nota: 5, status: "assistido", sinopse: "O herói enfrenta rivais comerciais e um vingador armado enquanto lida com os efeitos colaterais de sua tecnologia.", corTema: "#7a2020" },
  { id: 103, titulo: "Thor", ano: 2011, diretor: "Kenneth Branagh", generos: ["acao", "fantasia"], duracao: 115, nota: 5, status: "assistido", sinopse: "Um príncipe asgardiano arrogante é exilado na Terra e precisa provar seu valor para recuperar seus poderes.", corTema: "#255c5c" },
  { id: 104, titulo: "Capitão América: O Primeiro Vingador", ano: 2011, diretor: "Joe Johnston", generos: ["acao", "aventura"], duracao: 124, nota: 5, status: "assistido", sinopse: "Um jovem franzino se transforma em super-soldado para combater uma organização nazista de ciência avançada.", corTema: "#8a6a3a" },
  { id: 105, titulo: "Os Vingadores", ano: 2012, diretor: "Joss Whedon", generos: ["acao", "ficcao"], duracao: 143, nota: 5, status: "assistido", sinopse: "Um grupo de heróis é reunido para deter uma invasão alienígena liderada por um deus renegado.", corTema: "#1f2d4d" },
  { id: 106, titulo: "Homem de Ferro 3", ano: 2013, diretor: "Shane Black", generos: ["acao", "ficcao"], duracao: 130, nota: 4, status: "assistido", sinopse: "Após um ataque terrorista à sua casa, o herói precisa se reconstruir sem contar com sua armadura.", corTema: "#7a2020" },
  { id: 107, titulo: "Thor: O Mundo Sombrio", ano: 2013, diretor: "Alan Taylor", generos: ["acao", "fantasia"], duracao: 112, nota: 4, status: "assistido", sinopse: "Uma ameaça ancestral força o deus do trovão a se aliar ao irmão adotivo para salvar os nove reinos.", corTema: "#255c5c" },
  { id: 108, titulo: "Capitão América 2: O Soldado Invernal", ano: 2014, diretor: "Anthony e Joe Russo", generos: ["acao", "suspense"], duracao: 136, nota: 5, status: "assistido", sinopse: "O herói descobre uma conspiração infiltrada dentro da própria organização para a qual trabalha.", corTema: "#5c1f3a" },
  { id: 109, titulo: "Guardiões da Galáxia", ano: 2014, diretor: "James Gunn", generos: ["acao", "aventura"], duracao: 121, nota: 5, status: "assistido", sinopse: "Um grupo heterogêneo de fora da lei se une para impedir que um artefato poderoso caia em mãos erradas.", corTema: "#8a6a3a" },
  { id: 110, titulo: "Vingadores: Era de Ultron", ano: 2015, diretor: "Joss Whedon", generos: ["acao", "ficcao"], duracao: 141, nota: 5, status: "assistido", sinopse: "Uma inteligência artificial criada para proteger o mundo se volta contra seus próprios criadores.", corTema: "#1f2d4d" },
  { id: 111, titulo: "Homem-Formiga", ano: 2015, diretor: "Peyton Reed", generos: ["acao", "comedia"], duracao: 117, nota: 5, status: "assistido", sinopse: "Um ex-ladrão ganha a capacidade de encolher para executar um golpe que pode salvar o mundo.", corTema: "#5c5c1f" },
  { id: 112, titulo: "Capitão América: Guerra Civil", ano: 2016, diretor: "Anthony e Joe Russo", generos: ["acao", "drama"], duracao: 147, nota: 5, status: "assistido", sinopse: "Uma divergência sobre supervisão governamental divide um grupo de heróis em dois lados opostos.", corTema: "#4a5d3a" },
  { id: 113, titulo: "Doutor Estranho", ano: 2016, diretor: "Scott Derrickson", generos: ["acao", "fantasia"], duracao: 115, nota: 5, status: "assistido", sinopse: "Um cirurgião arrogante busca cura para suas mãos feridas e descobre um mundo de magia e dimensões paralelas.", corTema: "#255c5c" },
  { id: 114, titulo: "Guardiões da Galáxia Vol. 2", ano: 2017, diretor: "James Gunn", generos: ["acao", "aventura"], duracao: 137, nota: 5, status: "assistido", sinopse: "O grupo intergaláctico enfrenta revelações sobre a verdadeira origem de um de seus membros.", corTema: "#8a6a3a" },
  { id: 115, titulo: "Homem-Aranha: De Volta ao Lar", ano: 2017, diretor: "Jon Watts", generos: ["acao", "aventura"], duracao: 133, nota: 5, status: "assistido", sinopse: "Um jovem herói tenta equilibrar a vida escolar com a responsabilidade de proteger seu bairro.", corTema: "#8a6a3a" },
  { id: 116, titulo: "Thor: Ragnarok", ano: 2017, diretor: "Taika Waititi", generos: ["acao", "comedia"], duracao: 130, nota: 5, status: "assistido", sinopse: "Preso em um planeta distante, o herói precisa retornar a tempo de impedir a destruição de seu reino.", corTema: "#5c5c1f" },
  { id: 117, titulo: "Pantera Negra", ano: 2018, diretor: "Ryan Coogler", generos: ["acao", "drama"], duracao: 134, nota: 5, status: "assistido", sinopse: "O novo rei de uma nação tecnologicamente avançada precisa defender o trono de um desafiante com um passado ligado à sua família.", corTema: "#4a5d3a" },
  { id: 118, titulo: "Vingadores: Guerra Infinita", ano: 2018, diretor: "Anthony e Joe Russo", generos: ["acao", "ficcao"], duracao: 149, nota: 5, status: "assistido", sinopse: "Um titã poderoso busca reunir artefatos cósmicos capazes de eliminar metade de toda a vida no universo.", corTema: "#1f2d4d" },
  { id: 119, titulo: "Homem-Formiga e a Vespa", ano: 2018, diretor: "Peyton Reed", generos: ["acao", "comedia"], duracao: 118, nota: 4, status: "assistido", sinopse: "Uma dupla de heróis embarca em uma missão de resgate em uma dimensão subatômica.", corTema: "#5c5c1f" },
  { id: 120, titulo: "Capitã Marvel", ano: 2019, diretor: "Anna Boden e Ryan Fleck", generos: ["acao", "ficcao"], duracao: 124, nota: 4, status: "assistido", sinopse: "Uma piloto com poderes cósmicos descobre memórias escondidas sobre seu passado na Terra.", corTema: "#1f2d4d" },
  { id: 121, titulo: "Vingadores: Ultimato", ano: 2019, diretor: "Anthony e Joe Russo", generos: ["acao", "ficcao"], duracao: 181, nota: 5, status: "assistido", sinopse: "Os heróis sobreviventes traçam um plano desesperado para reverter os efeitos de uma perda catastrófica.", corTema: "#1f2d4d" },
  { id: 122, titulo: "Homem-Aranha: Longe de Casa", ano: 2019, diretor: "Jon Watts", generos: ["acao", "aventura"], duracao: 129, nota: 5, status: "assistido", sinopse: "Durante uma viagem escolar pela Europa, o jovem herói é recrutado para enfrentar ameaças elementais.", corTema: "#8a6a3a" },
  { id: 123, titulo: "Shang-Chi e a Lenda dos Dez Anéis", ano: 2021, diretor: "Destin Daniel Cretton", generos: ["acao", "fantasia"], duracao: 132, nota: 5, status: "assistido", sinopse: "Um homem é forçado a confrontar o passado que deixou para trás ao ser puxado para a organização secreta do pai.", corTema: "#255c5c" },

  // ---- Quentin Tarantino ----
  { id: 124, titulo: "Cães de Aluguel", ano: 1992, diretor: "Quentin Tarantino", generos: ["crime", "suspense"], duracao: 99, nota: 0, status: "quero-assistir", sinopse: "Um assalto a joalheria dá errado e os criminosos sobreviventes suspeitam de um infiltrado entre eles.", corTema: "#3a3a3a" },
  { id: 125, titulo: "Pulp Fiction: Tempo de Violência", ano: 1994, diretor: "Quentin Tarantino", generos: ["crime", "drama"], duracao: 154, nota: 5, status: "assistido", sinopse: "Histórias entrelaçadas de capangas, um boxeador e um casal de assaltantes se cruzam em Los Angeles.", corTema: "#3a3a3a" },
  { id: 126, titulo: "Jackie Brown", ano: 1997, diretor: "Quentin Tarantino", generos: ["crime", "drama"], duracao: 154, nota: 0, status: "quero-assistir", sinopse: "Uma aeromoça presa contrabandeando dinheiro arma um plano arriscado para escapar de todos os lados envolvidos.", corTema: "#3a3a3a" },
  { id: 127, titulo: "Kill Bill: Volume 1", ano: 2003, diretor: "Quentin Tarantino", generos: ["acao", "crime"], duracao: 111, nota: 0, status: "quero-assistir", sinopse: "Uma ex-assassina desperta de um coma decidida a se vingar de quem tentou matá-la no altar.", corTema: "#7a2020" },
  { id: 128, titulo: "Kill Bill: Volume 2", ano: 2004, diretor: "Quentin Tarantino", generos: ["acao", "crime"], duracao: 137, nota: 0, status: "quero-assistir", sinopse: "A protagonista continua sua jornada de vingança até o confronto final com o líder do grupo que a traiu.", corTema: "#7a2020" },
  { id: 129, titulo: "À Prova de Morte", ano: 2007, diretor: "Quentin Tarantino", generos: ["acao", "suspense"], duracao: 113, nota: 0, status: "quero-assistir", sinopse: "Um dublê usa seu carro reforçado como arma para perseguir grupos de mulheres em estradas americanas.", corTema: "#5c1f3a" },
  { id: 130, titulo: "Bastardos Inglórios", ano: 2009, diretor: "Quentin Tarantino", generos: ["acao", "drama"], duracao: 153, nota: 5, status: "assistido", sinopse: "Um esquadrão de soldados judeus-americanos trama um plano para acabar com a liderança nazista na França ocupada.", corTema: "#4a5d3a" },
  { id: 131, titulo: "Django Livre", ano: 2012, diretor: "Quentin Tarantino", generos: ["aventura", "drama"], duracao: 165, nota: 5, status: "assistido", sinopse: "Um escravo libertado se une a um caçador de recompensas para resgatar sua esposa de um fazendeiro brutal.", corTema: "#8a6a3a" },
  { id: 132, titulo: "Os Oito Odiados", ano: 2015, diretor: "Quentin Tarantino", generos: ["suspense", "drama"], duracao: 168, nota: 0, status: "quero-assistir", sinopse: "Oito estranhos presos por uma nevasca em uma cabana isolada escondem segredos perigosos uns dos outros.", corTema: "#5c1f3a" },
  { id: 133, titulo: "Era Uma Vez em... Hollywood", ano: 2019, diretor: "Quentin Tarantino", generos: ["drama", "comedia"], duracao: 161, nota: 5, status: "assistido", sinopse: "Um ator em declínio e seu dublê tentam se manter relevantes na Hollywood de 1969.", corTema: "#5c5c1f" },

  // ---- Star Wars ----
  { id: 134, titulo: "Star Wars: Uma Nova Esperança", ano: 1977, diretor: "George Lucas", generos: ["ficcao", "aventura"], duracao: 121, nota: 0, status: "quero-assistir", sinopse: "Um jovem fazendeiro se junta à rebelião para resgatar uma princesa e destruir uma estação de combate colossal.", corTema: "#1f2d4d" },
  { id: 135, titulo: "Star Wars: O Império Contra-Ataca", ano: 1980, diretor: "Irvin Kershner", generos: ["ficcao", "aventura"], duracao: 124, nota: 0, status: "quero-assistir", sinopse: "Os rebeldes são caçados por um império vingativo enquanto o protagonista treina para se tornar um cavaleiro Jedi.", corTema: "#1f2d4d" },
  { id: 136, titulo: "Star Wars: O Retorno de Jedi", ano: 1983, diretor: "Richard Marquand", generos: ["ficcao", "aventura"], duracao: 131, nota: 0, status: "quero-assistir", sinopse: "A batalha final entre a rebelião e o império decide o destino da galáxia.", corTema: "#1f2d4d" },
  { id: 137, titulo: "Star Wars: A Ameaça Fantasma", ano: 1999, diretor: "George Lucas", generos: ["ficcao", "aventura"], duracao: 133, nota: 0, status: "quero-assistir", sinopse: "Dois Jedi protegem uma jovem rainha enquanto um plano político ameaça a estabilidade da república.", corTema: "#1f2d4d" },
  { id: 138, titulo: "Star Wars: Ataque dos Clones", ano: 2002, diretor: "George Lucas", generos: ["ficcao", "aventura"], duracao: 142, nota: 0, status: "quero-assistir", sinopse: "Um exército de clones surge em meio a uma crise separatista que ameaça dividir a galáxia.", corTema: "#1f2d4d" },
  { id: 139, titulo: "Star Wars: A Vingança dos Sith", ano: 2005, diretor: "George Lucas", generos: ["ficcao", "aventura"], duracao: 140, nota: 0, status: "quero-assistir", sinopse: "Um Jedi promissor sucumbe ao lado sombrio da força, selando o destino da república.", corTema: "#1f2d4d" },
  { id: 140, titulo: "Star Wars: O Despertar da Força", ano: 2015, diretor: "J.J. Abrams", generos: ["ficcao", "aventura"], duracao: 138, nota: 0, status: "quero-assistir", sinopse: "Uma nova geração de heróis entra em rota de colisão com os remanescentes do antigo império.", corTema: "#1f2d4d" },
  { id: 141, titulo: "Star Wars: Os Últimos Jedi", ano: 2017, diretor: "Rian Johnson", generos: ["ficcao", "aventura"], duracao: 152, nota: 0, status: "quero-assistir", sinopse: "Uma jovem em busca de treinamento Jedi confronta as crenças de um mestre isolado e desiludido.", corTema: "#1f2d4d" },
  { id: 142, titulo: "Star Wars: A Ascensão Skywalker", ano: 2019, diretor: "J.J. Abrams", generos: ["ficcao", "aventura"], duracao: 142, nota: 0, status: "quero-assistir", sinopse: "A resistência enfrenta o retorno de uma ameaça sombria que parecia definitivamente derrotada.", corTema: "#1f2d4d" },

  // ---- Batman / DC ----
  { id: 143, titulo: "Batman Begins", ano: 2005, diretor: "Christopher Nolan", generos: ["acao", "drama"], duracao: 140, nota: 5, status: "assistido", sinopse: "Um herdeiro traumatizado treina no exterior antes de voltar à sua cidade natal para combater o crime.", corTema: "#7a2020" },
  { id: 144, titulo: "Batman: O Cavaleiro das Trevas", ano: 2008, diretor: "Christopher Nolan", generos: ["acao", "crime"], duracao: 152, nota: 5, status: "assistido", sinopse: "Um vigilante mascarado enfrenta um criminoso caótico que testa seus limites morais.", corTema: "#3a3a3a" },
  { id: 145, titulo: "Batman: O Cavaleiro das Trevas Ressurge", ano: 2012, diretor: "Christopher Nolan", generos: ["acao", "drama"], duracao: 165, nota: 5, status: "assistido", sinopse: "Anos após se retirar, o herói é forçado a voltar quando um novo vilão ameaça destruir sua cidade.", corTema: "#7a2020" },
  { id: 146, titulo: "Homem de Aço", ano: 2013, diretor: "Zack Snyder", generos: ["acao", "ficcao"], duracao: 143, nota: 5, status: "assistido", sinopse: "Um alienígena criado na Terra precisa decidir entre esconder seus poderes ou proteger a humanidade.", corTema: "#1f2d4d" },
  { id: 147, titulo: "Liga da Justiça", ano: 2017, diretor: "Zack Snyder", generos: ["acao", "ficcao"], duracao: 120, nota: 3, status: "assistido", sinopse: "Um grupo de heróis se une para enfrentar uma ameaça alienígena após a perda de um aliado importante.", corTema: "#1f2d4d" },
  { id: 148, titulo: "Mulher-Maravilha", ano: 2017, diretor: "Patty Jenkins", generos: ["acao", "fantasia"], duracao: 141, nota: 5, status: "assistido", sinopse: "Uma guerreira amazona deixa sua ilha isolada para combater as forças por trás da Primeira Guerra Mundial.", corTema: "#255c5c" },
  { id: 149, titulo: "The Batman", ano: 2022, diretor: "Matt Reeves", generos: ["acao", "crime"], duracao: 176, nota: 5, status: "assistido", sinopse: "No segundo ano como vigilante, o herói investiga uma série de assassinatos ligados à corrupção da cidade.", corTema: "#3a3a3a" },

  // ---- Harry Potter ----
  { id: 150, titulo: "Harry Potter e a Pedra Filosofal", ano: 2001, diretor: "Chris Columbus", generos: ["fantasia", "aventura"], duracao: 152, nota: 5, status: "assistido", sinopse: "Um garoto órfão descobre ser bruxo e ingressa em uma escola de magia repleta de mistérios.", corTema: "#255c5c" },
  { id: 151, titulo: "Harry Potter e a Câmara Secreta", ano: 2002, diretor: "Chris Columbus", generos: ["fantasia", "aventura"], duracao: 161, nota: 5, status: "assistido", sinopse: "Uma série de ataques misteriosos na escola de magia reacende uma lenda antiga e perigosa.", corTema: "#255c5c" },
  { id: 152, titulo: "Harry Potter e o Prisioneiro de Azkaban", ano: 2004, diretor: "Alfonso Cuarón", generos: ["fantasia", "aventura"], duracao: 142, nota: 5, status: "assistido", sinopse: "A fuga de um prisioneiro perigoso traz revelações sobre o passado da família do protagonista.", corTema: "#255c5c" },
  { id: 153, titulo: "Harry Potter e o Cálice de Fogo", ano: 2005, diretor: "Mike Newell", generos: ["fantasia", "aventura"], duracao: 157, nota: 5, status: "assistido", sinopse: "Um torneio mágico entre escolas coloca o protagonista em perigo mortal sem que ele tenha se inscrito.", corTema: "#255c5c" },
  { id: 154, titulo: "Harry Potter e a Ordem da Fênix", ano: 2007, diretor: "David Yates", generos: ["fantasia", "aventura"], duracao: 138, nota: 5, status: "assistido", sinopse: "Enquanto o ministério nega o retorno do mal, um grupo de estudantes se prepara secretamente para a resistência.", corTema: "#255c5c" },
  { id: 155, titulo: "Harry Potter e o Enigma do Príncipe", ano: 2009, diretor: "David Yates", generos: ["fantasia", "aventura"], duracao: 153, nota: 4, status: "assistido", sinopse: "Aulas particulares revelam memórias-chave sobre o passado do maior inimigo do protagonista.", corTema: "#255c5c" },
  { id: 156, titulo: "Harry Potter e as Relíquias da Morte: Parte 1", ano: 2010, diretor: "David Yates", generos: ["fantasia", "aventura"], duracao: 146, nota: 4, status: "assistido", sinopse: "Os protagonistas partem em uma jornada perigosa para destruir os fragmentos da alma do vilão.", corTema: "#255c5c" },
  { id: 157, titulo: "Harry Potter e as Relíquias da Morte: Parte 2", ano: 2011, diretor: "David Yates", generos: ["fantasia", "aventura"], duracao: 130, nota: 5, status: "assistido", sinopse: "A batalha final pela escola de magia decide o destino de todo o mundo bruxo.", corTema: "#255c5c" },

  // ---- O Senhor dos Anéis / O Hobbit ----
  { id: 158, titulo: "O Senhor dos Anéis: A Sociedade do Anel", ano: 2001, diretor: "Peter Jackson", generos: ["fantasia", "aventura"], duracao: 178, nota: 0, status: "quero-assistir", sinopse: "Um hobbit assume a missão de destruir um anel amaldiçoado antes que ele caia nas mãos erradas.", corTema: "#8a6a3a" },
  { id: 159, titulo: "O Senhor dos Anéis: As Duas Torres", ano: 2002, diretor: "Peter Jackson", generos: ["fantasia", "aventura"], duracao: 179, nota: 0, status: "quero-assistir", sinopse: "A comunidade dividida enfrenta batalhas separadas enquanto o portador do anel se aproxima de seu destino.", corTema: "#8a6a3a" },
  { id: 160, titulo: "O Senhor dos Anéis: O Retorno do Rei", ano: 2003, diretor: "Peter Jackson", generos: ["fantasia", "aventura"], duracao: 201, nota: 0, status: "quero-assistir", sinopse: "As forças livres da Terra-média se unem para a batalha final contra um exército sombrio.", corTema: "#8a6a3a" },
  { id: 161, titulo: "O Hobbit: Uma Jornada Inesperada", ano: 2012, diretor: "Peter Jackson", generos: ["fantasia", "aventura"], duracao: 169, nota: 0, status: "quero-assistir", sinopse: "Um hobbit pacato é recrutado por um grupo de anões para recuperar um reino tomado por um dragão.", corTema: "#8a6a3a" },
  { id: 162, titulo: "O Hobbit: A Desolação de Smaug", ano: 2013, diretor: "Peter Jackson", generos: ["fantasia", "aventura"], duracao: 161, nota: 0, status: "quero-assistir", sinopse: "O grupo se aproxima da montanha solitária e de seu perigoso guardião alado.", corTema: "#8a6a3a" },
  { id: 163, titulo: "O Hobbit: A Batalha dos Cinco Exércitos", ano: 2014, diretor: "Peter Jackson", generos: ["fantasia", "aventura"], duracao: 144, nota: 0, status: "quero-assistir", sinopse: "A disputa pelo tesouro do reino recuperado desencadeia um conflito entre vários povos da Terra-média.", corTema: "#8a6a3a" },
